language: php
dist: xenial

php:
  - 7.3

services:
  - mysql

cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"

branches:
  only:
  - /^8\.([0-9]+|x)\-[0-9]+\.([0-9]+|x)$/

env:
  global:
    - PATH="$PATH:$HOME/.composer/vendor/bin"

matrix:
  include:
    - env: DRUPAL_TESTING_DRUPAL_VERSION=~9.0.0
    - env: DRUPAL_TESTING_DRUPAL_VERSION=~8.9.0
    - env: DRUPAL_TESTING_DRUPAL_VERSION=~8.8.0
    - env: DRUPAL_TESTING_DRUPAL_VERSION=~8.7.0

before_install:
  - composer global require thunder/drupal-testing

before_script:
  - phpenv config-rm xdebug.ini

script:
  - test-drupal-project

notifications:
  email: false
