language: php
sudo: required

cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"

php:
  - 7.2
  - 5.6

branches:
  only:
  - /^8\.([0-9]+|x)\-[0-9]+\.([0-9]+|x)$/
  - test/deprecations

env:
  global:
    - PATH="$PATH:$HOME/.composer/vendor/bin"
    - DRUPAL_TRAVIS_TEST_JAVASCRIPT=false

before_install:
  - composer global require thunder/travis:dev-feature/php-stan

script:
  - test-drupal-project

notifications:
  email: false
